export const labels = {
  appTitle: "FX Journal MVP",
  nextActionTitle: "次にやること",
  tradePre: "取引前（30秒）",
  tradePost: "取引後（60秒）",
  skip: "見送り（15秒）",
  weeklyLimitReached: "今週の上限に達しました。次は見送りを記録してください。",
  incompleteNotice: "未完が1件あります。完了すると記録が締まります。",
  adminTitle: "管理/先生ポータル",
  adminTodo: "今日やること（3つ）",
  adminTodoFollowup: "未完に声をかける",
  adminTodoReview: "レビューする",
  adminTodoSafety: "安全確認",
  adminQueueFollowup: "未完に声をかける",
  adminQueueReview: "レビューする（3択）",
  adminQueueRisk: "安全確認DM",
  adminQueueUnlock: "解放する/保留",
  adminActionFollowup: "催促DM",
  adminActionReview: "レビューする",
  adminActionSafety: "確認DM",
  adminUnlock: "解放",
  adminLogs: "ログ閲覧",
  reviewOk: "構造OK",
  reviewWarn: "構造ズレ",
  reviewInspect: "検証対象",
};
